const slides = [
  { kicker: 'Урок 01', title: 'История развития нейросетей', text: 'Как технология прошла путь от научной идеи до помощника в повседневной жизни.', visual: '<div class="neural"><i></i><i></i><i></i><i></i><b>AI</b></div>', className: 'cover' },
  { kicker: 'Основное понятие', title: 'Что такое искусственный интеллект?', text: 'Технологии, которые помогают компьютеру распознавать, прогнозировать, создавать и решать задачи.', points: ['Анализирует', 'Находит связи', 'Предлагает результат'] },
  { kicker: 'Один из способов создать ИИ', title: 'Что такое нейросеть?', text: 'Математическая модель из связанных элементов. Она обучается на множестве примеров.', quote: 'Нейросеть вычисляет — но не думает и не чувствует как человек.' },
  { kicker: 'Четыре этапа', title: 'Как обучается нейросеть', flow: ['Данные', 'Обучение', 'Закономерности', 'Результат'], text: 'Качество результата зависит от примеров, задачи и проверки человеком.' },
  { kicker: 'Короткая история', title: 'От идеи к генеративному ИИ', timeline: [['1950-е','Первые идеи'],['1956','Термин AI'],['1990–2000-е','Машинное обучение'],['2010-е','Глубокое обучение'],['Сегодня','Генеративные модели']] },
  { kicker: 'Применение', title: 'ИИ в образовании', text: 'Технология помогает подобрать объяснение, создать тренировочные задания и получить обратную связь.', points: ['Персональный темп', 'Новые форматы', 'Помощь учителю'], quote: 'ИИ — помощник в обучении, а не замена самостоятельному мышлению.' },
  { kicker: 'Применение', title: 'Медицина и транспорт', split: [{ icon:'⚕', title:'Медицина', text:'Анализ снимков и больших наборов данных.' },{ icon:'↗', title:'Транспорт', text:'Маршруты, прогноз пробок и распознавание объектов.' }] },
  { kicker: 'Творчество', title: 'Генеративные нейросети', text: 'Создают новый материал на основе закономерностей, найденных в данных.', points: ['Тексты', 'Изображения', 'Музыка и видео'] },
  { kicker: 'Ответственное использование', title: 'Возможности и ограничения', split: [{ icon:'✓', title:'Возможности', text:'Скорость, анализ, идеи и автоматизация.' },{ icon:'!', title:'Ограничения', text:'Ошибки, смещения в данных и неточные ответы.' }], quote: 'Важную информацию всегда проверяйте по надёжным источникам.' },
  { kicker: 'Подведём итог', title: 'Вопросы для обсуждения', questions: ['Где вы встретили нейросеть сегодня?', 'Какую задачу она решала?', 'Почему её ответ нужно проверять?'], text: 'ИИ усиливает идеи человека, когда мы используем его осознанно.' }
];
const container = document.querySelector('#slides');
function markup(slide, index) { return `<section class="slide ${slide.className || ''}" data-slide="${index}"><div class="slide-copy"><p class="kicker">${slide.kicker}</p><h1>${slide.title}</h1>${slide.text ? `<p class="lead">${slide.text}</p>` : ''}${slide.points ? `<div class="slide-points">${slide.points.map((p,i)=>`<div><b>0${i+1}</b>${p}</div>`).join('')}</div>` : ''}${slide.flow ? `<div class="slide-flow">${slide.flow.map(p=>`<span>${p}</span>`).join('<i>→</i>')}</div>` : ''}${slide.timeline ? `<div class="slide-timeline">${slide.timeline.map(p=>`<div><b>${p[0]}</b><span>${p[1]}</span></div>`).join('')}</div>` : ''}${slide.split ? `<div class="slide-split">${slide.split.map(p=>`<div><b>${p.icon}</b><h2>${p.title}</h2><p>${p.text}</p></div>`).join('')}</div>` : ''}${slide.questions ? `<div class="slide-questions">${slide.questions.map(q=>`<p>${q}</p>`).join('')}</div>` : ''}${slide.quote ? `<blockquote>${slide.quote}</blockquote>` : ''}</div>${slide.visual || ''}<span class="slide-number">${String(index+1).padStart(2,'0')}</span></section>`; }
container.innerHTML = slides.map(markup).join('');
let current = 0;
function show(index) { current = Math.max(0,Math.min(slides.length-1,index)); document.querySelectorAll('.slide').forEach((s,i)=>s.classList.toggle('active',i===current)); document.querySelector('#counter').textContent=`${current+1} / ${slides.length}`; document.querySelector('#deck-progress-fill').style.width=`${(current+1)/slides.length*100}%`; document.querySelector('#prev').disabled=current===0; document.querySelector('#next').disabled=current===slides.length-1; }
document.querySelector('#prev').addEventListener('click',()=>show(current-1)); document.querySelector('#next').addEventListener('click',()=>show(current+1));
document.addEventListener('keydown',event=>{if(['ArrowRight',' '].includes(event.key))show(current+1);if(event.key==='ArrowLeft')show(current-1);if(event.key==='Escape'&&document.fullscreenElement)document.exitFullscreen();});
document.querySelector('#fullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()); let touch=0;container.addEventListener('touchstart',e=>touch=e.touches[0].clientX,{passive:true});container.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-touch;if(Math.abs(d)>50)show(current+(d<0?1:-1));},{passive:true});show(0);
